name: Test
on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Install Playwright Dependencies
        run: npx playwright install-deps
      - name: Unit Tests
        run: yarn rw test --no-watch
      - name: E2E Tests
      - uses: microsoft/playwright-github-action@v1
        run: yarn exec cd web && npx playwright test
